on: [push]
jobs:
  verify:
    name: Verify Application
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '14'

      - run: npm ci
        name: Install Dependencies

      - run: npm test
        name: Run Unit Tests
  deploy:
    name: Deploy to GH Pages
    runs-on: ubuntu-20.04
    needs: [verify]
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '14'

      - run: npm ci
        name: Install Dependencies

      - run: npm run build
        name: Build Application

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
